alias v='vim'
alias c='clear'
alias untar='tar -xsvf'
alias zshrc='vim -p ~/.zshrc ~/.zsh/aliases.sh && source ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias addex="sudo chmod a+rwx"
alias lf='vim $LAST_FILE'
alias ipy='ipython3'
alias python='python3'
alias pytohn='python3'
alias ls='lsd'
alias j='z'
alias music='ncmpcpp --screen=media_library'
alias emoj='emoji-fzf preview --prepend | fzf -m --preview "emoji-fzf get --name {2}" | awk "{ print \$1 }"'
